---
driver:
  name: terraform
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

platforms:
  - name: ubuntu

transport:
  name: ssh
  ssh_key: ~/.ssh/id_rsa

verifier:
  name: terraform
  format: doc
  groups:
  - name: default
  controls:
  - operating_system
  hostnames: public_dns
  username: ubuntu

suites:
  - name: default
